Norwegian sbert
ScandinavianSection-UCLA/Norwegian_NLP pull request #2
Opened 2023-02-22 22:10 UTC by mithunansiva

In the untitled notebook (Need to change the name) I have tested the nb s-bert. It seems like this could be fine-tuned. This is trained on multinli (https://cims.nyu.edu/~sbowman/multinli/). And bascially only in bokmål.

2023-02-23 01:08 UTC, Mariuble approved these changes

2023-02-23 22:15 UTC, AndreasWintherMoen commented
Should probably gitignore .DS_STORE 😉 

![bitmoji](https://sdk.bitmoji.com/render/panel/c7583a5d-6d79-49ff-b3fc-9a44438f62ee-34ecf193-27bc-400d-b0e0-397282d0b9a4-v1.png?transparent=1&palette=1&width=246)

2023-02-23 22:32 UTC, Mariuble requested changes
Legg .DS_Store til i .gitignore. Som Andreas sa ;)

2023-02-24 01:23 UTC, Mariuble approved these changes

2023-03-01 02:46 UTC, merged